source 'https://github.com/CocoaPods/Specs.git'

target 'PINCHTextRendering', :exclusive => true do
  pod "PINCHTextRendering", :path => "../"
end

target 'Tests', :exclusive => true do
#  pod "PINCHTextRendering", :path => "../"

  pod 'Specta'
  pod 'Expecta'
  pod 'Expecta+Snapshots', :git => 'https://github.com/dblock/ios-snapshot-test-case-expecta.git'
end
